name: conda_hidapi
channels:
  - conda-forge
  - auto
  - defaults
dependencies:
  - commonmark
  - libusb
  - python=3.8.5
  - sphinx
  - sphinx_rtd_theme
  - gcc_linux-64
  - libudev-devel-cos6-x86_64